### ISSUE TITLE
Hue Dimmer Switch appears as a light bulb

### ISSUE THREAD

**Issue by mvoss96** [itavero/homebridge-z2m#1]
Hi,
thanks for this software. 
It seems that the Hue dimmer Switch gets recognized as a light bulb which is not correct.
Not sure whether you can fix this or if its an Issue with home kit

**Comment by itavero** [comment]
Can you provide me with the MQTT message zigbee2mqtt sends for this device? (As I don't have one myself)

**Comment by itavero** [comment]
By the way, I just released a version that allows you to exclude devices from the Homebridge integration by adding their IEEE address to the `config.json` (or via `homebridge-ui-x`). There is an example in the README.
It's not a fix for you problem, but at least it will help you get rid of the incorrect device for the time being.

**Comment by mvoss96** [comment]
Hi, this is the content of the zigbee2mqtt config message:
` {
    "ieeeAddr": "0x0017880106e85acb",
    "type": "EndDevice",
    "networkAddress": 41612,
    "model": "324131092621",
    "vendor": "Philips",
    "description": "Hue dimmer switch",
    "friendly_name": "Dimmer_Switch",
    "manufacturerID": 4107,
    "manufacturerName": "Philips",
    "powerSource": "Battery",
    "modelID": "RWL021",
    "hardwareVersion": 1,
    "softwareBuildID": "6.1.1.28573",
    "dateCode": "20190410",
    "lastSeen": 1593637842215
},'`

Thanks for the new feature. I will happily try it later.

**Comment by mvoss96** [comment]
when the buttons on the DImmer switch are pressed, the messages look like this:
`{"battery":100,"linkquality":34,"update_available":false,"counter":1,"brightness":255,"action":"up-hold-release","duration":1.851}`
`{"battery":100,"linkquality":34,"update_available":false,"counter":1,"brightness":255,"action":"up-hold-release","duration":1.851}`

**Comment by itavero** [comment]
It doesn't have the `state` property that I've seen on all lights so far, so it should be a rather simple fix to at least not add it as a Lightbulb.

Unfortunately remote controls (push buttons) are not yet supported (see #2). They turned out to be a lot more difficult to handle than simple temperature sensors and lightbulbs.

**Comment by itavero** [comment]
@mvoss96 I added an additional check so that the `state` property must also be present to detect a Lightbulb. This should resolve the fact that your dimmer switch is recognized as a Lightbulb.

As mentioned, for "remote control" support, keep an eye on #2.

The changes are currently in the `master` branch, but not yet released.
If you want you can [already try them](https://github.com/itavero/homebridge-z2m#testing-the-latest-changes).

If the erroneous detection of a lightbulb still occurs, we can reopen this issue ;)

**Comment by itavero** [comment]
FYI: Published a new release that includes the fix for this issue.
