### ISSUE TITLE
[Bug] AQARA MCCGQ14LM temperature value missing

### ISSUE THREAD

**Issue by JanLue4** [itavero/homebridge-z2m#342]
**Describe the bug**
In the new Aqara E1 Windows Sensor the temperature value is missing in home bridge an HomeKit, like it is available in the "old" MCCGQ11LM Device

In the MQTT Logs there is show the entry. In my other System (FHEM) the temperature value ist correct.

**Related devices**
I have two of the Devices withe the same missing temperature value, at the "old" aqara devices, I have more of them the temperature reading is displayed in homebridge and HomeKit  

**MQTT messages**
From zigbee2mqtt Log: 
MQTT publish: topic 'zigbee2mqtt/Fenster_Kueche_links', payload '{"battery":97,"battery_low":false,"contact":true,"linkquality":102,"state":"OFF","tamper":false,"temperature":25,"voltage":2994}'

From Homebridge Log in Debug Mode:
[29.12.2021, 08:56:38] [zigbee2mqtt] Handled device update for Fenster_Kueche_links: {"battery":97,"battery_low":false,"contact":false,"linkquality":97,"state":"OFF","tamper":false,"temperature":25,"voltage":2994}

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin: 1.6.2
 - Homebridge: 1.3.9
 - Zigbee2MQTT: 1.22.1 
 - Homebridge Config UI X (if applicable): 4.41.5

I'am a beginner in mqtt home bridge and zigbee, so sorry if I made mistakes, and sorry for my poor English too :-(

**Comment by itavero** [comment]
It seems that it is not included in the _Exposes_ information of this device. You did not include this information in your bug report, but I can tell from looking at the [device page on zigbee2mqtt.io](https://www.zigbee2mqtt.io/devices/MCCGQ14LM.html) that it is missing.

This can be fixed in [Koenkk/zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters).
If it indeed supports a temperature, it should be added in [devices/xiaomi.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/xiaomi.js#L45) to the `exposes` of the `MCCGQ14LM` entry.
As you can see in that same file, the `MCCGQ11LM` has `e.temperature()` in their `exposes`.

I'd suggest to raise an issue or create a pull request for that repository.
As soon as the fix is included in a zigbee2mqtt release and you update to that version, homebridge-z2m will automatically pick it up.

**Comment by JanLue4** [comment]
@itavero Thank you very much for the quick reply and support!
