### ISSUE TITLE
[Device] Immax 07703L Radiator valve

### ISSUE THREAD

**Issue by jukben** [itavero/homebridge-z2m#37]
Hey! Thanks for awesome project, first of all I would like to say I'm super newbie in this one. I just bought Raspberry Pi 4 B and https://slae.sh/projects/cc2652/ and I decided to play with it. I tried some Ikea bulb I found around and works fine (I had to post initial message manually to get recognized properly, but I know you are looking into it – not a big deal)

I would say I have capabilities to make this contribution on my own, but would be great if you/someone can guide me. How does it sound? Can we hop on call?

--- 

**Device description**
Which device would you like to be supported in this plugin? 

[Immax 07703L Radiator valve](https://www.immaxneo.cz/produkty/immax-neo-smart-termostaticka-hlavice-zigbee/)

**Supported in zigbee2mqtt?** ✅

**Device model / Exposes information**

```json
"definition": {
      "description": "Radiator valve",
      "exposes": [
        {
          "access": 1,
          "description": "Indicates if the battery of this device is almost empty",
          "name": "battery_low",
          "property": "battery_low",
          "type": "binary",
          "value_off": false,
          "value_on": true
        },
        {
          "features": [
            {
              "access": 7,
              "description": "Enables/disables physical input on the device",
              "name": "state",
              "property": "child_lock",
              "type": "binary",
              "value_off": "UNLOCK",
              "value_on": "LOCK"
            }
          ],
          "type": "lock"
        },
        {
          "features": [
            {
              "access": 7,
              "description": "Temperature setpoint",
              "name": "current_heating_setpoint",
              "property": "current_heating_setpoint",
              "type": "numeric",
              "unit": "°C",
              "value_max": 35,
              "value_min": 5,
              "value_step": 0.5
            },
            {
              "access": 5,
              "description": "Current temperature measured on the device",
              "name": "local_temperature",
              "property": "local_temperature",
              "type": "numeric",
              "unit": "°C"
            },
            {
              "access": 7,
              "description": "Mode of this device",
              "name": "system_mode",
              "property": "system_mode",
              "type": "enum",
              "values": ["off", "heat", "auto"]
            },
            {
              "access": 5,
              "description": "The current running state",
              "name": "running_state",
              "property": "running_state",
              "type": "enum",
              "values": ["idle", "heat"]
            },
            {
              "access": 7,
              "description": "Away mode",
              "name": "away_mode",
              "property": "away_mode",
              "type": "binary",
              "value_off": "OFF",
              "value_on": "ON"
            }
          ],
          "type": "climate"
        },
        {
          "access": 1,
          "description": "Link quality (signal strength)",
          "name": "linkquality",
          "property": "linkquality",
          "type": "numeric",
          "unit": "lqi",
          "value_max": 255,
          "value_min": 0
        }
      ],
      "model": "07703L",
      "vendor": "Immax"
    },
 ```

**Missing features/functionality**

Everyting AFIK – it acts as unsupported device

**Suggested services and characteristics**

I don't have experiences with smart valves but I would expect:

- Temperature 
- Valve

**Comment by itavero** [comment]
I don't think this can be mapped as a _Valve_.
I think `climate` should be mapped to a _Heater Cooler_ or a _Thermostat_ (which also provide the temperature already).

Probably requires the same implementation as for #35

Thanks for providing the information.
I'm first finishing up the support for push buttons (which is pretty much the oldest issue still open for this plugin).
I hope I'll be able to start on this implementation somewhere in the next weeks.
As mentioned in the other issue, I won't be able to fully test this, as I do not have these kind of devices.

**Comment by jukben** [comment]
Awesome, thanks for reply. You are right about Thermostat 👍 Makes sense. 

There is (just for the record) sample communication:

```
Jan 09 16:36:05 homebridge npm[467]: Zigbee2MQTT:info  2021-01-09 16:36:05: MQTT publish: topic 'zigbee2mqtt/valve-workroom', payload '{"away_mode":"OFF","battery_low":"OFF","child_lock":"UNLOCKED","current_heating_setpoint":"21.0","device_offline":"OFF","external_sensor_error":"OFF","high_temperature":"OFF","internal_sensor_error":"OFF","linkquality":48,"local_temperature":"22.0","low_temperature":"OFF","preset":"none","running_state":"idle","system_mode":"heat"}'
Jan 09 16:41:05 homebridge npm[467]: Zigbee2MQTT:info  2021-01-09 16:41:05: MQTT publish: topic 'zigbee2mqtt/valve-workroom', payload '{"away_mode":"OFF","battery_low":"OFF","child_lock":"UNLOCKED","current_heating_setpoint":"21.0","device_offline":"OFF","external_sensor_error":"OFF","high_temperature":"OFF","internal_sensor_error":"OFF","linkquality":51,"local_temperature":"22.0","low_temperature":"OFF","preset":"none","running_state":"idle","system_mode":"heat"}'
```

I would even try to implement it on my own, but I don't really know where to start. Any chance you can actually point me in the right direction?

**Comment by itavero** [comment]
I can give you some pointers, but I don't have any detailed instructions on how stuff is setup.
In `src/converters` you will find the different implementations of the devices currently implemented. I think this particular case it makes most sense to first have a look at how `switch.ts` is setup (it's a rather simple device) and then maybe look at `light.ts`, which is a bit more complicated and has some optional features.
As you might be able to tell these files contain a "factory" (the `ServiceCreator`, i.e. `SwitchCreator`) that filters and/or groups the exposes information in order to construct and register a `ServiceHandler` (i.e. `SwitchHandler`).

In the `test` folder there are some "integration" tests, that verify if the `ServiceHandler` is created when given a certain device JSON, and if updates from MQTT result in updated characteristics and if updating characteristics from HomeKit result in an MQTT message.

Personally I'm first probably going to work on making the online/offline state of zigbee2mqtt (and specific devices, if availability is turned on in zigbee2mqtt) visible via HomeKit. After that I'll have time to start the implementation of the handler for thermostats/radiator valves (`climate` devices) as well.

**Comment by jukben** [comment]
Thanks a lot @itavero, I will try to look around. Would you recommend to run separate DEV homebridge instance? This is rather general question for any Homebridge development. I will let you know if I have something, in a meantime, good luck and take care. 🙏

**Comment by itavero** [comment]
I use a separate Homebridge instance for development to test things (running on my MacBook where I'm developing).
My "production" Homebridge is running on my home server via Docker.

I would not recommend doing development on your "production" environment, unless you make a lot of backups.
On my development environment I don't mind if I have to throw away my `~/.homebridge/` folder, but I'd rather not start over on my "production" environment.

Most of the times I do use the same MQTT server and thus the same zigbee2mqtt instance. Although I have worked with running zigbee2mqtt on my laptop as well (with the same MQTT server but a different base_topic).
In general, this is not needed though.

Within the Home app on the iPhone, I've added a separate "test home", next to my actual home.
This is done so I don't bother my spouse and so that I can clearly distinguish between the two instances fo Homebridge.
The only annoying thing with having a "test home" is that my iPhone sometimes "jumps" back to my actual home. I think this is because I have an Apple TV acting as a gateway and it is on the same network as my iPhone.

**Comment by jukben** [comment]
Awesome, great tips. Thanks a lot! 👍

**Comment by Kepro** [comment]
@jukben I got the same devices today :D if you have anything done share your fork or something I will check that too

**Comment by jukben** [comment]
> @jukben I got the same devices today :D if you have anything done share your fork or something I will check that too

Unfortunately, nothing yet. I will give it another try this weekend, but I have to admit it's pretty hard to start. The abstraction is bit complex, so there is steep curve 😅

**Comment by itavero** [comment]
> The abstraction is bit complex, so there is steep curve 😅
Sorry for that. If you have suggestions/improvements, I'd love to hear them. Also, if there are specific things that I can explain that would help you get started, let me know.

I must admit that I'm a bit short on spare time since this week, because one of our alpacas 🦙 gave birth Monday morning and we weren't even aware that she was pregnant. Given that it's winter over here and it's our first cria [baby alpaca] it consumes quite a bit of time figuring things out and keeping an eye on her. Not your everyday "problem", I guess. 😆

*But*, since there seems to be quite some "demand" for `climate` device support, I have moved it to the top of my list. Whenever I do have a couple of hours to spare again, I'll try to start working on it.
In the meantime, please also see #32.

**Comment by itavero** [comment]
Opened up #40 to group all the individual request for thermostat/TRV support in one place, as these will most likely be handled by the same code.

Because of that I'm closing this issue. Updates/discussion should be done in this new issue.

**Comment by jukben** [comment]
Haha @itavero! That's sweet! Any picture of baby alpacas? 

Thanks for making it priority, however no pressure! OSS is not life! :D
