### ISSUE TITLE
[Feature] Custom action mapping (IKEA E1743)

### ISSUE THREAD

**Issue by StefanNienhuis** [itavero/homebridge-z2m#435]
**Problem description**
Currently my IKEA E1743 exposes four actions to this plugin: on, off, brightness_move_up and brightness_move_down. These are interpreted as four separate buttons, even though the brightness up and down buttons are the actions for long pressing the buttons.

**Suggested solution**
We could either modify the SwitchActionHelper in `src/converters/action_helper.ts` to recognise these brightness commands, but that would likely result in some ugly code and possible interference with other devices.

A better solution in my opinion would be to add a new config property to the `devices` array that allows you to map certain properties in the MQTT messages to different values. The syntax would be similar to the `values` property.

Example:
```json
{
    "devices": [
        {
            "id": "...",
            "mappings": [
                {
                    "property": "action",
                    "values": {
                        "on": "single_on",
                        "off": "single_off",
                        "brightness_move_up": "hold_on",
                        "brightness_move_down": "hold_off"
                    }
                }
            ]
        }
    ]
}
```

After these mappings are applied, the SwitchActionHelper would map these to the correct buttons.

**Describe alternatives you've considered**
Having all the actions as separate buttons is doable, but this would be my preference.

**Additional context**
n/a

**Are you willing to contribute to this feature?**
Yes, I'd be able to work on a PR if a maintainer approves of this feature.

**Comment by itavero** [comment]
I think in reality the problem here is that the actions have been named inconsistently compared to other remotes.
What do you really gain from it other than that it shows two buttons instead of 4?
Functionally it does not allow you to do anything new, right?

The plugin already allows you to [override the exposes information](https://z2m.dev/config.html#devices) as a whole for a device.
And, although I'm not familiar with it myself, I believe you could add a [user extension to Zigbee2MQTT](https://www.zigbee2mqtt.io/advanced/more/user_extensions.html) to send/translate the values on that side.
So, you could solve it that way perhaps.

My goal for this plugin has always been to need as little configuration as possible.
Even though this does not directly break that rule, it does feel a bit like a hack.
