### ISSUE TITLE
[Feature] Choose different services than default

### ISSUE THREAD

**Issue by nitaybz** [itavero/homebridge-z2m#45]
Hey,

Thanks for the awesome plugin!

It would be super cool if services would be able to change in the plugin config. in my case, using occupancy sensors instead of motion sensor does not represent well my home so I would love to change occupancy to motion sensors in HomeKit.

I also thought it would be nice to have it dynamically available for all sorts of properties and services.
for example, possible changes users would might like to use:
occupancy -> contact sensor
switch -> lock (I connected a normal switch that control a dry relay of a gate lock for example)
switch -> valve

and i'm sure there are many other changes users would want to make, mostly with boolean state like true/false or on/off

Thanks in advanced

**Comment by itavero** [comment]
Thanks for your feature request.

Would you mind to make a proposal for what the plugin configuration should look like for this feature in your opinion?

**Comment by nitaybz** [comment]
I would do that all the binary accessories, divided to 2 groups, would be able to change the accessory type within their group:

1. Binary sensors that only report status but can't set/change state: motion, occupancy, button, contact, smoke, leak, and maybe more that I'm missing.

2. Binary accessories that can be controlled and set/change state: switch, lock, outlet, (maybe valve?).

Since all those devices report 0 or 1 we can change the type of accessory represented in the home app without a problem, only need to map the HAP accessories states and zigbee accessories state to 0 and 1.

Hope I made it clear

**Comment by itavero** [comment]
But what would the configuration in the JSON file look like?
Also consider that a single device can have multiple binary characteristics.

**Comment by AndrewStef7** [comment]
Hey, I am sorry for intervening. I used [homebridge-mqttthing](url) until yesterday. It worked fine, but I wanted to change it because I could not get a status update when I was manually pressed a plug button. The thing I like so much about it is that you can configure everything for a device.

Here is an example of configuring a Silvercrest Plug:
> {
            "type": "outlet",
            "name": "Glob",
            "logMqtt": true,
            "topics": {
                "getOn": {
                    "topic": "zigbee2mqtt/0xec1bbdfffeb6120d/get/",
                    "apply": "return JSON.stringify({state: null})"
                },
                "setOn": {
                    "topic": "zigbee2mqtt/0xec1bbdfffeb6120d/set/",
                    "apply": "return JSON.stringify({state: message})"
                },
                "getInUse": "zigbee2mqtt/0xec1bbdfffeb6120d/get/state"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "onlineValue": "ON",
            "offlineValue": "OFF",
            "retryLimit": 3,
            "history": false,
            "turnOffAfterms": 0,
            "manufacturer": "Tecnodidattica Ligure S.p.A.",
            "serialNumber": "Andr3wSt3f",
            "model": "25W, E14",
            "firmwareRevision": "1.0",
            "accessory": "mqttthing"
        },

**Comment by itavero** [comment]
@AndrewStef7 The goal of this plugin is to have it working "out of the box" for most of the users, without any device configuration. The thing is that the example configuration can't be taken over "as is" within how this plugin is configured.

Personally I don't have time at the moment to work out what the plugin configuration should look like for this feature, so that's why I'm asking for others to contribute. 😄

**Comment by nitaybz** [comment]
Since it's already in the plugin settings to change settings for specific device I would just add another field named: accessoryType.
I would allow changing types between the groups I suggested, in any case you have more services you can add them to the newly created one, if they are binary too, and identical to the main service they should change too to the new type. If someone use a type which is not allow it can fallback to the original and show a message in the logs.

Hope it is clear

**Comment by itavero** [comment]
@nitaybz But that doesn't work. As mentioned, a single accessory can expose multiple services/characteristics (i.e. the [Oujiabao CR701-YZ](https://z2m.dev/devices/oujiabao/cr701-yz.html) exposes both a binary sensor for Carbon Monoxide and for gas leaks).

**Comment by nitaybz** [comment]
I would just exclude those with specific destination like carbon and maybe leaks and smoke...
You can start with simple:
occupancy-contact-motion
switch-outlet-lock

And add more in the future if users request it specifically

**Comment by itavero** [comment]
But if we don't take that scenario into account now with how the configuration is setup, then it's likely that in the future there will be a breaking change when someone requests it for a different type of device.

By the way, you can't simply switch from a [Switch](https://developers.homebridge.io/#/service/Switch) service to a [Lock Mechanism](https://developers.homebridge.io/#/service/LockMechanism). A lock isn't just a single binary state on Zigbee nor on HomeKit.

Apparently the [Outlet](https://developers.homebridge.io/#/service/Outlet) service no longer requires the _Outlet In Use_ characteristic, so that would be feasible.

**Comment by nitaybz** [comment]
any progress on this matter?
can we at least make something as small as occupancy to motion sensor?

**Comment by itavero** [comment]
> any progress on this matter?

No progress on it from my side.
It's not really on the top of my list (as there are a few feature request that more people have asked for and are also on my personal "wishlist").

> can we at least make something as small as occupancy to motion sensor?

It can probably be done, but I want to have a uniform way of configuring this.
Perhaps it should be set based on the name of one of the MQTT properties (I haven't given this a lot of thought or gone over what this would mean for the code base, but it came to mind while writing this reply).

**Comment by Tyraenor** [comment]
As it is long ago that someone wrote to this topic, I want to say that it would be really great to define an outlet as outlet in homekit, as it makes a difference in how to address it with Siri, as well as the really annoying look, that an outlet is displayed as a switch.

This would be really great.
