### ISSUE TITLE
[Feature] include no_occupancy_since (Mqtt msg) as a motion sensor to be used as a trigger for automation in Homekit

### ISSUE THREAD

**Issue by TzachiGuetta** [itavero/homebridge-z2m#482]
Hi, @itavero,
I'm suggesting to add new Motion sensor in Homekit - when the  no_occupancy_since is configured per device.
in this way we can use it as a trigger in Homekit automation (to turn of the light when no_occupancy_since occurred - for example)

**Comment by itavero** [comment]
Can you describe how this should be mapped and/or configured in the plugin? I'm not familiar with this Zigbee2MQTT feature, so a bit more background info is appreciated.

I personally use the homebridge-hourglass plugin for something like this I believe, because I have multiple sensors in the same zone (the garden).
I think there's also an Occupancy Delay plugin.
So perhaps you can also solve it that way, although I can also understand that it could make sense to use what you already have, rather than adding more plugins to the setup.
