### ISSUE TITLE
Expose Alarm as  Switch ON/OFF

### ISSUE THREAD

**Issue by rionshin** [itavero/homebridge-z2m#504]
I am using NAS-AB02B0  Zigbee Alarm   https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html#neo-nas-ab02b0 
it is supported by Zigbee2Mqqt and can be triggered by MQQT : To write (/set) a value publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"alarm": NEW_VALUE}. If value equals true alarm is ON, if false OFF.

This is everything exposed by MQQT"  and I need Switch for "ALARM" with TRUE/FALSE

{
"alarm":false,
"battery_low":false,
"humidity":54,
"humidity_alarm":false,
"humidity_max":80,
"humidity_min":30,
"linkquality":201,
"melody":1,
"power_type":"usb",
"temperature":27.1,
"temperature_alarm":false,
"temperature_max":35,
"temperature_min":10,
"volume":"low"}

**Problem description**
Expose Alarm as Switch in Homebridge 

**Suggested solution**
Expose Alarm as Switch with TRUE/FALSE 

**Describe alternatives you've considered**
I don't have any alternatives for the moment 

**Additional context**
screenshot attached 

**Are you willing to contribute to this feature?**
Yes - i will help , with whatever is necessary . 

<img width="1873" alt="Screenshot 2022-08-23 at 20 23 55" src="https://user-images.githubusercontent.com/41396180/186225082-166f556d-3e6c-4d9c-8b6a-1e2ab697418f.png">

**Comment by rionshin** [comment]
> For these kind of devices, I would suggest to use homebridge-mqtthing so you can configure it exactly as suits your needs.

I kinda agree, however when you buy a Siren you expect to be able to turn it on/off via Z2M :) And I See Zigbee2MQQT expose this atributаs as Switches but its not exposed as that in Z2M. 

I will play with MQQTThing, i just think it will be great to include such basics switches on alarms where ALARM is present with TRUE/FALSE.

**Comment by itavero** [comment]
A lot of these devices also have a lot of different "tones" and strobe patterns and such.
Adding switches for all combinations would mean adding a lot of switches, where I would expect that most users would only need a few combinations at most.
That's why I stayed away from these device types in this plugin, as it would most likely always require configuration, which is what I'm trying to avoid.

This device is slightly different than most of the devices I've seen as it also has a simple boolean trigger. But I'm not sure how many of those kind of devices are currently supported in Zigbee2MQTT, I'd have to check.

Besides using homebridge-mqtthing, you can also try to override the `exposes` information for this device in the plugin information, to make the plugin think it's a switch.

If I don't forget I'll see if the Matter specification defines anything similar to such a device.
I would expect so given that most (if not all) definitions from the Zigbee standard have been taken over.
Perhaps you might be in luck in the future. 😅

**Comment by rionshin** [comment]
Honestly, i think that only Switch for Alarm ON/OFF is enough, all other option can be setup in Zigbee2MQQT Interface and no need to expose all melodies and things, just the Switch for alarm on/off so it can be used easily in  Automations in Homekit - on something happen ON alarm.  

I am trying to use the MQTTing but with no luck it doesn't work at all and don't publish  the state :( 
i am trying but nothing is send to MQQT Broker , maybe i am not doing something correct as i am not so good with JS :( 

"topics": {
                "getOn": {
                    "topic": "zigbee2mqtt/Siren",
                    "apply": "return JSON.parse(message).alarm === 'true' ? true : false;"
                },
                "setOn": {
                    "topic": "zigbee2mqtt/Siren/set",
                    "apply": "return JSON.stringify({alarm: (message ? \"true\" : \"false\")});"
                }
            }


> A lot of these devices also have a lot of different "tones" and strobe patterns and such. Adding switches for all combinations would mean adding a lot of switches, where I would expect that most users would only need a few combinations at most. That's why I stayed away from these device types in this plugin, as it would most likely always require configuration, which is what I'm trying to avoid.
> 
> This device is slightly different than most of the devices I've seen as it also has a simple boolean trigger. But I'm not sure how many of those kind of devices are currently supported in Zigbee2MQTT, I'd have to check.
> 
> Besides using homebridge-mqtthing, you can also try to override the `exposes` information for this device in the plugin information, to make the plugin think it's a switch.
> 
> If I don't forget I'll see if the Matter specification defines anything similar to such a device. I would expect so given that most (if not all) definitions from the Zigbee standard have been taken over. Perhaps you might be in luck in the future. 😅
