### ISSUE TITLE
Heat/Auto not showing in homekit.

### ISSUE THREAD

**Issue by Stianker1** [itavero/homebridge-z2m#549]
Hello,
I just added a zigbee device to z2m ( Connecte Smart thermostat model : 4500994)
I'm running in to the problem that i cant see the Auto/Heat text inside the button.
is this something you could take a look at? 
(see attached picture)

best regards,
Stian 
![D04751E8-C3DF-472E-B667-BDF3D07C1BC7](https://user-images.githubusercontent.com/98734897/198573856-8f88cc1d-d25c-4d7b-ac71-446c2147f6fd.jpeg)

**Comment by itavero** [comment]
Please fill in all the data requested below, which was also asked for in the Bug Report issue template.

**Describe the bug**
A clear and concise description of what the bug is.

**Related devices**
Are you experiencing this behavior with a particular device?
Please list which device(s) you experience this with.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change '...' via the Home app.
2. Log shows MQTT message '...' being published to topic '...'
3. The device does the following: '...'

**Expected behavior**
A clear and concise description of what you expected to happen, compared to what actually happened.

**MQTT messages**
If possible (and applicable), please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)
* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
* Messages published by this plugin that might be related to your issue (can also be seen in the homebridge logs)

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin
 - Homebridge
 - Zigbee2MQTT (can be found in MQTT topic `zigbee2mqtt/bridge/info`)
 - Homebridge Config UI X (if applicable)
